language: go

go: "1.11.x"

env:
  - GO111MODULE=on CGO_ENABLED=0


install:
  - go build

script:
  - bash ./test.sh
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - if [ ! -z ${TRAVIS_TAG} ] || [ ${TRAVIS_BRANCH} == "master" ];
    then
      docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
    fi
  - if [ ! -z ${TRAVIS_TAG} ];
    then
      docker build . -t ${TRAVIS_REPO_SLUG}:${TRAVIS_TAG};
      docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_TAG};
    fi
  - if [ ${TRAVIS_BRANCH} == "master" ];
    then
      docker build . -t ${TRAVIS_REPO_SLUG}:latest;
      docker push ${TRAVIS_REPO_SLUG}:latest;
    fi
      