name: Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash ./test.sh
          bash <(curl -s https://codecov.io/bash)

      - name: Docker Login
        run: |
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Latest
        if: github.ref == 'master'
        run: |
          docker build . -t docker.pkg.github.com/julienduchesne/pull-request-reminder:latest
          docker push docker.pkg.github.com/julienduchesne/pull-request-reminder:latest

      - name: Build Tag
        if: github.ref != 'master'
        run: |
          docker build . -t docker.pkg.github.com/julienduchesne/pull-request-reminder:${{ github.ref }}
          docker push docker.pkg.github.com/julienduchesne/pull-request-reminder:${{ github.ref }}
