name: Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Build
        run: go build -v

      - name: Run Tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash ./test.sh
          bash <(curl -s https://codecov.io/bash)

      - name: Docker Login
        run: |
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker build . -t docker.pkg.github.com/julienduchesne/pull-request-reminder/alpine:latest
          docker push docker.pkg.github.com/julienduchesne/pull-request-reminder/alpine:latest

      - name: Build Tag
        if: github.ref != 'refs/heads/master'
        run: |
          export tag=$(cut -d'/' -f3 <<<'${{ github.ref }}')
          docker build . -t docker.pkg.github.com/julienduchesne/pull-request-reminder/alpine:$tag
          docker push docker.pkg.github.com/julienduchesne/pull-request-reminder/alpine:$tag
